name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      FLASH_ATTENTION_VERSION:
        description: "Flash Attention version"
        required: true
        default: "98edb0d29bb1db336fef845fb5fd49bc98b04b96"
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build Wheel
    runs-on: depot-ubuntu-latest-64
    env:
      FLASH_ATTENTION_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.FLASH_ATTENTION_VERSION || '98edb0d29bb1db336fef845fb5fd49bc98b04b96' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
            torch-version: '2.4.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.10'
            torch-version: '2.5.1'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.10'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.10'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.11'
            torch-version: '2.4.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.11'
            torch-version: '2.5.1'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.11'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.11'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.12'
            torch-version: '2.4.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.12'
            torch-version: '2.5.1'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.12'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'
          - python-version: '3.12'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'FALSE'       
          - python-version: '3.10'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'
          - python-version: '3.10'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'
          - python-version: '3.11'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'
          - python-version: '3.11'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'
          - python-version: '3.12'
            torch-version: '2.6.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'
          - python-version: '3.12'
            torch-version: '2.7.0'
            cuda-version: '12.8.1'
            cxx11_abi: 'TRUE'

    steps:
      - name: Checkout Flash Attention
        uses: actions/checkout@v4
        with:
          repository: Dao-AILab/flash-attention
          ref: ${{ env.FLASH_ATTENTION_VERSION }}

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          path: build_scripts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set CUDA and PyTorch versions
        run: |
          echo "MATRIX_CUDA_VERSION=$(echo ${{ matrix.cuda-version }} | awk -F \. {'print $1 $2'})" >> $GITHUB_ENV
          echo "MATRIX_TORCH_VERSION=$(echo ${{ matrix.torch-version }} | awk -F \. {'print $1 "." $2'})" >> $GITHUB_ENV
          echo "WHEEL_CUDA_VERSION=$(echo ${{ matrix.cuda-version }} | awk -F \. {'print $1'})" >> $GITHUB_ENV
          echo "MATRIX_PYTHON_VERSION=$(echo ${{ matrix.python-version }} | awk -F \. {'print $1 $2'})" >> $GITHUB_ENV

      - name: Free up disk space
        if: ${{ runner.os == 'Linux' }}
        # https://github.com/easimon/maximize-build-space/blob/master/action.yml
        # https://github.com/easimon/maximize-build-space/tree/test-report
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Install CUDA ${{ matrix.cuda-version }}
        if: ${{ matrix.cuda-version != 'cpu' }}
        uses: Jimver/cuda-toolkit@v0.2.23
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
          linux-local-args: '["--toolkit"]'
          # default method is "local", and we're hitting some error with caching for CUDA 11.8 and 12.1
          # method: ${{ (matrix.cuda-version == '11.8.0' || matrix.cuda-version == '12.1.0') && 'network' || 'local' }}
          method: "network"

      - name: List CUDA include directory
        run: ls /usr/local/cuda-12.8/include/

      - name: Install PyTorch ${{ matrix.torch-version }}+cu${{ matrix.cuda-version }}
        working-directory: ./hopper
        run: |
          pip install --upgrade pip
          # With python 3.13 and torch 2.5.1, unless we update typing-extensions, we get error
          # AttributeError: attribute '__default__' of 'typing.ParamSpec' objects is not writable
          pip install typing-extensions==4.12.2
          # We want to figure out the CUDA version to download pytorch
          # e.g. we can have system CUDA version being 11.7 but if torch==1.12 then we need to download the wheel from cu116
          # see https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix
          # This code is ugly, maybe there's a better way to do this.
          export TORCH_CUDA_VERSION=$(python -c "from os import environ as env; \
            minv = {'2.4': 118, '2.5': 118, '2.6': 118, '2.7': 118}[env['MATRIX_TORCH_VERSION']]; \
            maxv = {'2.4': 124, '2.5': 124, '2.6': 126, '2.7': 128}[env['MATRIX_TORCH_VERSION']]; \
            print(minv if int(env['MATRIX_CUDA_VERSION']) < 120 else maxv)" \
          )
          pip install --no-cache-dir torch==${{ matrix.torch-version }} --index-url https://download.pytorch.org/whl/cu${TORCH_CUDA_VERSION}
          nvcc --version
          python --version
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import torch; print('CUDA:', torch.version.cuda)"
          python -c "from torch.utils import cpp_extension; print (cpp_extension.CUDA_HOME)"
        shell: bash

      - name: Build wheel
        working-directory: ./hopper
        run: |
          pip install setuptools ninja packaging wheel
          export PATH=/usr/local/nvidia/bin:/usr/local/nvidia/lib64:$PATH
          export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
          # Limit MAX_JOBS otherwise the github runner goes OOM
          # nvcc 11.8 can compile with 2 jobs, but nvcc 12.3 goes OOM
          MAX_JOBS=16 FLASH_ATTENTION_FORCE_BUILD="TRUE" FLASH_ATTENTION_FORCE_CXX11_ABI=${{ matrix.cxx11_abi}} python setup.py bdist_wheel --dist-dir=dist
          tmpname=cu${WHEEL_CUDA_VERSION}torch${MATRIX_TORCH_VERSION}cxx11abi${{ matrix.cxx11_abi }}
          wheel_name=$(ls dist/*whl | xargs -n 1 basename | sed "s/-/+$tmpname-/2")
          ls dist/*whl |xargs -I {} mv {} dist/${wheel_name}
          echo "wheel_name=${wheel_name}" >> $GITHUB_ENV

      - name: Log Built Wheels
        run: |
          wheel_name=$(ls hopper/dist/*whl | xargs -n 1 basename)
          echo "wheel_name=${wheel_name}" >> $GITHUB_ENV
          ls hopper/dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.wheel_name}}
          path: hopper/dist/${{env.wheel_name}}
          if-no-files-found: error
